// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/moca/testprotobuf/proto/Student.proto

package com.moca.testprotobuf.proto;

public final class ProtoDemo {
	private ProtoDemo() {
	}

	public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
	}

	public interface StudentOrBuilder extends com.google.protobuf.MessageOrBuilder {

		// required int32 id = 1;
		/**
		 * <code>required int32 id = 1;</code>
		 */
		boolean hasId();

		/**
		 * <code>required int32 id = 1;</code>
		 */
		int getId();

		// required string name = 2;
		/**
		 * <code>required string name = 2;</code>
		 */
		boolean hasName();

		/**
		 * <code>required string name = 2;</code>
		 */
		java.lang.String getName();

		/**
		 * <code>required string name = 2;</code>
		 */
		com.google.protobuf.ByteString getNameBytes();

		// optional string email = 3;
		/**
		 * <code>optional string email = 3;</code>
		 */
		boolean hasEmail();

		/**
		 * <code>optional string email = 3;</code>
		 */
		java.lang.String getEmail();

		/**
		 * <code>optional string email = 3;</code>
		 */
		com.google.protobuf.ByteString getEmailBytes();

		// optional .proto.Student.Sex sex = 4 [default = MAN];
		/**
		 * <code>optional .proto.Student.Sex sex = 4 [default = MAN];</code>
		 */
		boolean hasSex();

		/**
		 * <code>optional .proto.Student.Sex sex = 4 [default = MAN];</code>
		 */
		com.moca.testprotobuf.proto.ProtoDemo.Student.Sex getSex();

		// repeated .proto.Student.PhoneNumber phone = 5;
		/**
		 * <code>repeated .proto.Student.PhoneNumber phone = 5;</code>
		 */
		java.util.List<com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber> getPhoneList();

		/**
		 * <code>repeated .proto.Student.PhoneNumber phone = 5;</code>
		 */
		com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber getPhone(int index);

		/**
		 * <code>repeated .proto.Student.PhoneNumber phone = 5;</code>
		 */
		int getPhoneCount();

		/**
		 * <code>repeated .proto.Student.PhoneNumber phone = 5;</code>
		 */
		java.util.List<? extends com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumberOrBuilder> getPhoneOrBuilderList();

		/**
		 * <code>repeated .proto.Student.PhoneNumber phone = 5;</code>
		 */
		com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumberOrBuilder getPhoneOrBuilder(int index);
	}

	/**
	 * Protobuf type {@code proto.Student}
	 */
	public static final class Student extends com.google.protobuf.GeneratedMessage implements StudentOrBuilder {
		// Use Student.newBuilder() to construct.
		private Student(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
			super(builder);
			this.unknownFields = builder.getUnknownFields();
		}

		private Student(boolean noInit) {
			this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
		}

		private static final Student defaultInstance;

		public static Student getDefaultInstance() {
			return defaultInstance;
		}

		public Student getDefaultInstanceForType() {
			return defaultInstance;
		}

		private final com.google.protobuf.UnknownFieldSet unknownFields;

		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
			return this.unknownFields;
		}

		private Student(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			initFields();
			int mutable_bitField0_ = 0;
			com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
					.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						done = true;
						break;
					default: {
						if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
							done = true;
						}
						break;
					}
					case 8: {
						bitField0_ |= 0x00000001;
						id_ = input.readInt32();
						break;
					}
					case 18: {
						bitField0_ |= 0x00000002;
						name_ = input.readBytes();
						break;
					}
					case 26: {
						bitField0_ |= 0x00000004;
						email_ = input.readBytes();
						break;
					}
					case 32: {
						int rawValue = input.readEnum();
						com.moca.testprotobuf.proto.ProtoDemo.Student.Sex value = com.moca.testprotobuf.proto.ProtoDemo.Student.Sex
								.valueOf(rawValue);
						if (value == null) {
							unknownFields.mergeVarintField(4, rawValue);
						} else {
							bitField0_ |= 0x00000008;
							sex_ = value;
						}
						break;
					}
					case 42: {
						if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
							phone_ = new java.util.ArrayList<com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber>();
							mutable_bitField0_ |= 0x00000010;
						}
						phone_.add(input.readMessage(com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber.PARSER,
								extensionRegistry));
						break;
					}
					}
				}
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(e.getMessage()).setUnfinishedMessage(this);
			} finally {
				if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
					phone_ = java.util.Collections.unmodifiableList(phone_);
				}
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return com.moca.testprotobuf.proto.ProtoDemo.internal_static_proto_Student_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return com.moca.testprotobuf.proto.ProtoDemo.internal_static_proto_Student_fieldAccessorTable
					.ensureFieldAccessorsInitialized(com.moca.testprotobuf.proto.ProtoDemo.Student.class,
							com.moca.testprotobuf.proto.ProtoDemo.Student.Builder.class);
		}

		public static com.google.protobuf.Parser<Student> PARSER = new com.google.protobuf.AbstractParser<Student>() {
			public Student parsePartialFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return new Student(input, extensionRegistry);
			}
		};

		@java.lang.Override
		public com.google.protobuf.Parser<Student> getParserForType() {
			return PARSER;
		}

		/**
		 * Protobuf enum {@code proto.Student.Sex}
		 */
		public enum Sex implements com.google.protobuf.ProtocolMessageEnum {
			/**
			 * <code>MAN = 0;</code>
			 */
			MAN(0, 0),
			/**
			 * <code>WOMAN = 1;</code>
			 */
			WOMAN(1, 1),;

			/**
			 * <code>MAN = 0;</code>
			 */
			public static final int MAN_VALUE = 0;
			/**
			 * <code>WOMAN = 1;</code>
			 */
			public static final int WOMAN_VALUE = 1;

			public final int getNumber() {
				return value;
			}

			public static Sex valueOf(int value) {
				switch (value) {
				case 0:
					return MAN;
				case 1:
					return WOMAN;
				default:
					return null;
				}
			}

			public static com.google.protobuf.Internal.EnumLiteMap<Sex> internalGetValueMap() {
				return internalValueMap;
			}

			private static com.google.protobuf.Internal.EnumLiteMap<Sex> internalValueMap = new com.google.protobuf.Internal.EnumLiteMap<Sex>() {
				public Sex findValueByNumber(int number) {
					return Sex.valueOf(number);
				}
			};

			public final com.google.protobuf.Descriptors.EnumValueDescriptor getValueDescriptor() {
				return getDescriptor().getValues().get(index);
			}

			public final com.google.protobuf.Descriptors.EnumDescriptor getDescriptorForType() {
				return getDescriptor();
			}

			public static final com.google.protobuf.Descriptors.EnumDescriptor getDescriptor() {
				return com.moca.testprotobuf.proto.ProtoDemo.Student.getDescriptor().getEnumTypes().get(0);
			}

			private static final Sex[] VALUES = values();

			public static Sex valueOf(com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
				if (desc.getType() != getDescriptor()) {
					throw new java.lang.IllegalArgumentException("EnumValueDescriptor is not for this type.");
				}
				return VALUES[desc.getIndex()];
			}

			private final int index;
			private final int value;

			private Sex(int index, int value) {
				this.index = index;
				this.value = value;
			}

			// @@protoc_insertion_point(enum_scope:proto.Student.Sex)
		}

		/**
		 * Protobuf enum {@code proto.Student.PhoneType}
		 */
		public enum PhoneType implements com.google.protobuf.ProtocolMessageEnum {
			/**
			 * <code>MOBILE = 0;</code>
			 */
			MOBILE(0, 0),
			/**
			 * <code>HOME = 1;</code>
			 */
			HOME(1, 1),
			/**
			 * <code>WORK = 2;</code>
			 */
			WORK(2, 2),;

			/**
			 * <code>MOBILE = 0;</code>
			 */
			public static final int MOBILE_VALUE = 0;
			/**
			 * <code>HOME = 1;</code>
			 */
			public static final int HOME_VALUE = 1;
			/**
			 * <code>WORK = 2;</code>
			 */
			public static final int WORK_VALUE = 2;

			public final int getNumber() {
				return value;
			}

			public static PhoneType valueOf(int value) {
				switch (value) {
				case 0:
					return MOBILE;
				case 1:
					return HOME;
				case 2:
					return WORK;
				default:
					return null;
				}
			}

			public static com.google.protobuf.Internal.EnumLiteMap<PhoneType> internalGetValueMap() {
				return internalValueMap;
			}

			private static com.google.protobuf.Internal.EnumLiteMap<PhoneType> internalValueMap = new com.google.protobuf.Internal.EnumLiteMap<PhoneType>() {
				public PhoneType findValueByNumber(int number) {
					return PhoneType.valueOf(number);
				}
			};

			public final com.google.protobuf.Descriptors.EnumValueDescriptor getValueDescriptor() {
				return getDescriptor().getValues().get(index);
			}

			public final com.google.protobuf.Descriptors.EnumDescriptor getDescriptorForType() {
				return getDescriptor();
			}

			public static final com.google.protobuf.Descriptors.EnumDescriptor getDescriptor() {
				return com.moca.testprotobuf.proto.ProtoDemo.Student.getDescriptor().getEnumTypes().get(1);
			}

			private static final PhoneType[] VALUES = values();

			public static PhoneType valueOf(com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
				if (desc.getType() != getDescriptor()) {
					throw new java.lang.IllegalArgumentException("EnumValueDescriptor is not for this type.");
				}
				return VALUES[desc.getIndex()];
			}

			private final int index;
			private final int value;

			private PhoneType(int index, int value) {
				this.index = index;
				this.value = value;
			}

			// @@protoc_insertion_point(enum_scope:proto.Student.PhoneType)
		}

		public interface PhoneNumberOrBuilder extends com.google.protobuf.MessageOrBuilder {

			// required string number = 1;
			/**
			 * <code>required string number = 1;</code>
			 */
			boolean hasNumber();

			/**
			 * <code>required string number = 1;</code>
			 */
			java.lang.String getNumber();

			/**
			 * <code>required string number = 1;</code>
			 */
			com.google.protobuf.ByteString getNumberBytes();

			// optional .proto.Student.PhoneType type = 2 [default = HOME];
			/**
			 * <code>optional .proto.Student.PhoneType type = 2 [default = HOME];</code>
			 */
			boolean hasType();

			/**
			 * <code>optional .proto.Student.PhoneType type = 2 [default = HOME];</code>
			 */
			com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneType getType();
		}

		/**
		 * Protobuf type {@code proto.Student.PhoneNumber}
		 */
		public static final class PhoneNumber extends com.google.protobuf.GeneratedMessage
				implements PhoneNumberOrBuilder {
			// Use PhoneNumber.newBuilder() to construct.
			private PhoneNumber(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
				super(builder);
				this.unknownFields = builder.getUnknownFields();
			}

			private PhoneNumber(boolean noInit) {
				this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
			}

			private static final PhoneNumber defaultInstance;

			public static PhoneNumber getDefaultInstance() {
				return defaultInstance;
			}

			public PhoneNumber getDefaultInstanceForType() {
				return defaultInstance;
			}

			private final com.google.protobuf.UnknownFieldSet unknownFields;

			@java.lang.Override
			public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
				return this.unknownFields;
			}

			private PhoneNumber(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				initFields();
				int mutable_bitField0_ = 0;
				com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
						.newBuilder();
				try {
					boolean done = false;
					while (!done) {
						int tag = input.readTag();
						switch (tag) {
						case 0:
							done = true;
							break;
						default: {
							if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
								done = true;
							}
							break;
						}
						case 10: {
							bitField0_ |= 0x00000001;
							number_ = input.readBytes();
							break;
						}
						case 16: {
							int rawValue = input.readEnum();
							com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneType value = com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneType
									.valueOf(rawValue);
							if (value == null) {
								unknownFields.mergeVarintField(2, rawValue);
							} else {
								bitField0_ |= 0x00000002;
								type_ = value;
							}
							break;
						}
						}
					}
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					throw e.setUnfinishedMessage(this);
				} catch (java.io.IOException e) {
					throw new com.google.protobuf.InvalidProtocolBufferException(e.getMessage())
							.setUnfinishedMessage(this);
				} finally {
					this.unknownFields = unknownFields.build();
					makeExtensionsImmutable();
				}
			}

			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return com.moca.testprotobuf.proto.ProtoDemo.internal_static_proto_Student_PhoneNumber_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return com.moca.testprotobuf.proto.ProtoDemo.internal_static_proto_Student_PhoneNumber_fieldAccessorTable
						.ensureFieldAccessorsInitialized(
								com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber.class,
								com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber.Builder.class);
			}

			public static com.google.protobuf.Parser<PhoneNumber> PARSER = new com.google.protobuf.AbstractParser<PhoneNumber>() {
				public PhoneNumber parsePartialFrom(com.google.protobuf.CodedInputStream input,
						com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws com.google.protobuf.InvalidProtocolBufferException {
					return new PhoneNumber(input, extensionRegistry);
				}
			};

			@java.lang.Override
			public com.google.protobuf.Parser<PhoneNumber> getParserForType() {
				return PARSER;
			}

			private int bitField0_;
			// required string number = 1;
			public static final int NUMBER_FIELD_NUMBER = 1;
			private java.lang.Object number_;

			/**
			 * <code>required string number = 1;</code>
			 */
			public boolean hasNumber() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			/**
			 * <code>required string number = 1;</code>
			 */
			public java.lang.String getNumber() {
				java.lang.Object ref = number_;
				if (ref instanceof java.lang.String) {
					return (java.lang.String) ref;
				} else {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					if (bs.isValidUtf8()) {
						number_ = s;
					}
					return s;
				}
			}

			/**
			 * <code>required string number = 1;</code>
			 */
			public com.google.protobuf.ByteString getNumberBytes() {
				java.lang.Object ref = number_;
				if (ref instanceof java.lang.String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					number_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			// optional .proto.Student.PhoneType type = 2 [default = HOME];
			public static final int TYPE_FIELD_NUMBER = 2;
			private com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneType type_;

			/**
			 * <code>optional .proto.Student.PhoneType type = 2 [default = HOME];</code>
			 */
			public boolean hasType() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}

			/**
			 * <code>optional .proto.Student.PhoneType type = 2 [default = HOME];</code>
			 */
			public com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneType getType() {
				return type_;
			}

			private void initFields() {
				number_ = "";
				type_ = com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneType.HOME;
			}

			private byte memoizedIsInitialized = -1;

			public final boolean isInitialized() {
				byte isInitialized = memoizedIsInitialized;
				if (isInitialized != -1)
					return isInitialized == 1;

				if (!hasNumber()) {
					memoizedIsInitialized = 0;
					return false;
				}
				memoizedIsInitialized = 1;
				return true;
			}

			public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
				getSerializedSize();
				if (((bitField0_ & 0x00000001) == 0x00000001)) {
					output.writeBytes(1, getNumberBytes());
				}
				if (((bitField0_ & 0x00000002) == 0x00000002)) {
					output.writeEnum(2, type_.getNumber());
				}
				getUnknownFields().writeTo(output);
			}

			private int memoizedSerializedSize = -1;

			public int getSerializedSize() {
				int size = memoizedSerializedSize;
				if (size != -1)
					return size;

				size = 0;
				if (((bitField0_ & 0x00000001) == 0x00000001)) {
					size += com.google.protobuf.CodedOutputStream.computeBytesSize(1, getNumberBytes());
				}
				if (((bitField0_ & 0x00000002) == 0x00000002)) {
					size += com.google.protobuf.CodedOutputStream.computeEnumSize(2, type_.getNumber());
				}
				size += getUnknownFields().getSerializedSize();
				memoizedSerializedSize = size;
				return size;
			}

			private static final long serialVersionUID = 0L;

			@java.lang.Override
			protected java.lang.Object writeReplace() throws java.io.ObjectStreamException {
				return super.writeReplace();
			}

			public static com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber parseFrom(
					com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
				return PARSER.parseFrom(data);
			}

			public static com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber parseFrom(
					com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return PARSER.parseFrom(data, extensionRegistry);
			}

			public static com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber parseFrom(byte[] data)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return PARSER.parseFrom(data);
			}

			public static com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber parseFrom(byte[] data,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return PARSER.parseFrom(data, extensionRegistry);
			}

			public static com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber parseFrom(java.io.InputStream input)
					throws java.io.IOException {
				return PARSER.parseFrom(input);
			}

			public static com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber parseFrom(java.io.InputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				return PARSER.parseFrom(input, extensionRegistry);
			}

			public static com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber parseDelimitedFrom(
					java.io.InputStream input) throws java.io.IOException {
				return PARSER.parseDelimitedFrom(input);
			}

			public static com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber parseDelimitedFrom(
					java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				return PARSER.parseDelimitedFrom(input, extensionRegistry);
			}

			public static com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber parseFrom(
					com.google.protobuf.CodedInputStream input) throws java.io.IOException {
				return PARSER.parseFrom(input);
			}

			public static com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber parseFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				return PARSER.parseFrom(input, extensionRegistry);
			}

			public static Builder newBuilder() {
				return Builder.create();
			}

			public Builder newBuilderForType() {
				return newBuilder();
			}

			public static Builder newBuilder(com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber prototype) {
				return newBuilder().mergeFrom(prototype);
			}

			public Builder toBuilder() {
				return newBuilder(this);
			}

			@java.lang.Override
			protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
				Builder builder = new Builder(parent);
				return builder;
			}

			/**
			 * Protobuf type {@code proto.Student.PhoneNumber}
			 */
			public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder>
					implements com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumberOrBuilder {
				public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
					return com.moca.testprotobuf.proto.ProtoDemo.internal_static_proto_Student_PhoneNumber_descriptor;
				}

				protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
					return com.moca.testprotobuf.proto.ProtoDemo.internal_static_proto_Student_PhoneNumber_fieldAccessorTable
							.ensureFieldAccessorsInitialized(
									com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber.class,
									com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber.Builder.class);
				}

				// Construct using
				// com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber.newBuilder()
				private Builder() {
					maybeForceBuilderInitialization();
				}

				private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
					super(parent);
					maybeForceBuilderInitialization();
				}

				private void maybeForceBuilderInitialization() {
					if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
					}
				}

				private static Builder create() {
					return new Builder();
				}

				public Builder clear() {
					super.clear();
					number_ = "";
					bitField0_ = (bitField0_ & ~0x00000001);
					type_ = com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneType.HOME;
					bitField0_ = (bitField0_ & ~0x00000002);
					return this;
				}

				public Builder clone() {
					return create().mergeFrom(buildPartial());
				}

				public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
					return com.moca.testprotobuf.proto.ProtoDemo.internal_static_proto_Student_PhoneNumber_descriptor;
				}

				public com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber getDefaultInstanceForType() {
					return com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber.getDefaultInstance();
				}

				public com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber build() {
					com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber result = buildPartial();
					if (!result.isInitialized()) {
						throw newUninitializedMessageException(result);
					}
					return result;
				}

				public com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber buildPartial() {
					com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber result = new com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber(
							this);
					int from_bitField0_ = bitField0_;
					int to_bitField0_ = 0;
					if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
						to_bitField0_ |= 0x00000001;
					}
					result.number_ = number_;
					if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
						to_bitField0_ |= 0x00000002;
					}
					result.type_ = type_;
					result.bitField0_ = to_bitField0_;
					onBuilt();
					return result;
				}

				public Builder mergeFrom(com.google.protobuf.Message other) {
					if (other instanceof com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber) {
						return mergeFrom((com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber) other);
					} else {
						super.mergeFrom(other);
						return this;
					}
				}

				public Builder mergeFrom(com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber other) {
					if (other == com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber.getDefaultInstance())
						return this;
					if (other.hasNumber()) {
						bitField0_ |= 0x00000001;
						number_ = other.number_;
						onChanged();
					}
					if (other.hasType()) {
						setType(other.getType());
					}
					this.mergeUnknownFields(other.getUnknownFields());
					return this;
				}

				public final boolean isInitialized() {
					if (!hasNumber()) {

						return false;
					}
					return true;
				}

				public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
						com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
					com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber parsedMessage = null;
					try {
						parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
					} catch (com.google.protobuf.InvalidProtocolBufferException e) {
						parsedMessage = (com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber) e
								.getUnfinishedMessage();
						throw e;
					} finally {
						if (parsedMessage != null) {
							mergeFrom(parsedMessage);
						}
					}
					return this;
				}

				private int bitField0_;

				// required string number = 1;
				private java.lang.Object number_ = "";

				/**
				 * <code>required string number = 1;</code>
				 */
				public boolean hasNumber() {
					return ((bitField0_ & 0x00000001) == 0x00000001);
				}

				/**
				 * <code>required string number = 1;</code>
				 */
				public java.lang.String getNumber() {
					java.lang.Object ref = number_;
					if (!(ref instanceof java.lang.String)) {
						java.lang.String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
						number_ = s;
						return s;
					} else {
						return (java.lang.String) ref;
					}
				}

				/**
				 * <code>required string number = 1;</code>
				 */
				public com.google.protobuf.ByteString getNumberBytes() {
					java.lang.Object ref = number_;
					if (ref instanceof String) {
						com.google.protobuf.ByteString b = com.google.protobuf.ByteString
								.copyFromUtf8((java.lang.String) ref);
						number_ = b;
						return b;
					} else {
						return (com.google.protobuf.ByteString) ref;
					}
				}

				/**
				 * <code>required string number = 1;</code>
				 */
				public Builder setNumber(java.lang.String value) {
					if (value == null) {
						throw new NullPointerException();
					}
					bitField0_ |= 0x00000001;
					number_ = value;
					onChanged();
					return this;
				}

				/**
				 * <code>required string number = 1;</code>
				 */
				public Builder clearNumber() {
					bitField0_ = (bitField0_ & ~0x00000001);
					number_ = getDefaultInstance().getNumber();
					onChanged();
					return this;
				}

				/**
				 * <code>required string number = 1;</code>
				 */
				public Builder setNumberBytes(com.google.protobuf.ByteString value) {
					if (value == null) {
						throw new NullPointerException();
					}
					bitField0_ |= 0x00000001;
					number_ = value;
					onChanged();
					return this;
				}

				// optional .proto.Student.PhoneType type = 2 [default = HOME];
				private com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneType type_ = com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneType.HOME;

				/**
				 * <code>optional .proto.Student.PhoneType type = 2 [default = HOME];</code>
				 */
				public boolean hasType() {
					return ((bitField0_ & 0x00000002) == 0x00000002);
				}

				/**
				 * <code>optional .proto.Student.PhoneType type = 2 [default = HOME];</code>
				 */
				public com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneType getType() {
					return type_;
				}

				/**
				 * <code>optional .proto.Student.PhoneType type = 2 [default = HOME];</code>
				 */
				public Builder setType(com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneType value) {
					if (value == null) {
						throw new NullPointerException();
					}
					bitField0_ |= 0x00000002;
					type_ = value;
					onChanged();
					return this;
				}

				/**
				 * <code>optional .proto.Student.PhoneType type = 2 [default = HOME];</code>
				 */
				public Builder clearType() {
					bitField0_ = (bitField0_ & ~0x00000002);
					type_ = com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneType.HOME;
					onChanged();
					return this;
				}

				// @@protoc_insertion_point(builder_scope:proto.Student.PhoneNumber)
			}

			static {
				defaultInstance = new PhoneNumber(true);
				defaultInstance.initFields();
			}

			// @@protoc_insertion_point(class_scope:proto.Student.PhoneNumber)
		}

		private int bitField0_;
		// required int32 id = 1;
		public static final int ID_FIELD_NUMBER = 1;
		private int id_;

		/**
		 * <code>required int32 id = 1;</code>
		 */
		public boolean hasId() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		/**
		 * <code>required int32 id = 1;</code>
		 */
		public int getId() {
			return id_;
		}

		// required string name = 2;
		public static final int NAME_FIELD_NUMBER = 2;
		private java.lang.Object name_;

		/**
		 * <code>required string name = 2;</code>
		 */
		public boolean hasName() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}

		/**
		 * <code>required string name = 2;</code>
		 */
		public java.lang.String getName() {
			java.lang.Object ref = name_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				if (bs.isValidUtf8()) {
					name_ = s;
				}
				return s;
			}
		}

		/**
		 * <code>required string name = 2;</code>
		 */
		public com.google.protobuf.ByteString getNameBytes() {
			java.lang.Object ref = name_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				name_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		// optional string email = 3;
		public static final int EMAIL_FIELD_NUMBER = 3;
		private java.lang.Object email_;

		/**
		 * <code>optional string email = 3;</code>
		 */
		public boolean hasEmail() {
			return ((bitField0_ & 0x00000004) == 0x00000004);
		}

		/**
		 * <code>optional string email = 3;</code>
		 */
		public java.lang.String getEmail() {
			java.lang.Object ref = email_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				if (bs.isValidUtf8()) {
					email_ = s;
				}
				return s;
			}
		}

		/**
		 * <code>optional string email = 3;</code>
		 */
		public com.google.protobuf.ByteString getEmailBytes() {
			java.lang.Object ref = email_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				email_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		// optional .proto.Student.Sex sex = 4 [default = MAN];
		public static final int SEX_FIELD_NUMBER = 4;
		private com.moca.testprotobuf.proto.ProtoDemo.Student.Sex sex_;

		/**
		 * <code>optional .proto.Student.Sex sex = 4 [default = MAN];</code>
		 */
		public boolean hasSex() {
			return ((bitField0_ & 0x00000008) == 0x00000008);
		}

		/**
		 * <code>optional .proto.Student.Sex sex = 4 [default = MAN];</code>
		 */
		public com.moca.testprotobuf.proto.ProtoDemo.Student.Sex getSex() {
			return sex_;
		}

		// repeated .proto.Student.PhoneNumber phone = 5;
		public static final int PHONE_FIELD_NUMBER = 5;
		private java.util.List<com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber> phone_;

		/**
		 * <code>repeated .proto.Student.PhoneNumber phone = 5;</code>
		 */
		public java.util.List<com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber> getPhoneList() {
			return phone_;
		}

		/**
		 * <code>repeated .proto.Student.PhoneNumber phone = 5;</code>
		 */
		public java.util.List<? extends com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumberOrBuilder> getPhoneOrBuilderList() {
			return phone_;
		}

		/**
		 * <code>repeated .proto.Student.PhoneNumber phone = 5;</code>
		 */
		public int getPhoneCount() {
			return phone_.size();
		}

		/**
		 * <code>repeated .proto.Student.PhoneNumber phone = 5;</code>
		 */
		public com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber getPhone(int index) {
			return phone_.get(index);
		}

		/**
		 * <code>repeated .proto.Student.PhoneNumber phone = 5;</code>
		 */
		public com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumberOrBuilder getPhoneOrBuilder(int index) {
			return phone_.get(index);
		}

		private void initFields() {
			id_ = 0;
			name_ = "";
			email_ = "";
			sex_ = com.moca.testprotobuf.proto.ProtoDemo.Student.Sex.MAN;
			phone_ = java.util.Collections.emptyList();
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			if (!hasId()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasName()) {
				memoizedIsInitialized = 0;
				return false;
			}
			for (int i = 0; i < getPhoneCount(); i++) {
				if (!getPhone(i).isInitialized()) {
					memoizedIsInitialized = 0;
					return false;
				}
			}
			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeInt32(1, id_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeBytes(2, getNameBytes());
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				output.writeBytes(3, getEmailBytes());
			}
			if (((bitField0_ & 0x00000008) == 0x00000008)) {
				output.writeEnum(4, sex_.getNumber());
			}
			for (int i = 0; i < phone_.size(); i++) {
				output.writeMessage(5, phone_.get(i));
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(1, id_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(2, getNameBytes());
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(3, getEmailBytes());
			}
			if (((bitField0_ & 0x00000008) == 0x00000008)) {
				size += com.google.protobuf.CodedOutputStream.computeEnumSize(4, sex_.getNumber());
			}
			for (int i = 0; i < phone_.size(); i++) {
				size += com.google.protobuf.CodedOutputStream.computeMessageSize(5, phone_.get(i));
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace() throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static com.moca.testprotobuf.proto.ProtoDemo.Student parseFrom(com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static com.moca.testprotobuf.proto.ProtoDemo.Student parseFrom(com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static com.moca.testprotobuf.proto.ProtoDemo.Student parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static com.moca.testprotobuf.proto.ProtoDemo.Student parseFrom(byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static com.moca.testprotobuf.proto.ProtoDemo.Student parseFrom(java.io.InputStream input)
				throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static com.moca.testprotobuf.proto.ProtoDemo.Student parseFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static com.moca.testprotobuf.proto.ProtoDemo.Student parseDelimitedFrom(java.io.InputStream input)
				throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input);
		}

		public static com.moca.testprotobuf.proto.ProtoDemo.Student parseDelimitedFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input, extensionRegistry);
		}

		public static com.moca.testprotobuf.proto.ProtoDemo.Student parseFrom(
				com.google.protobuf.CodedInputStream input) throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static com.moca.testprotobuf.proto.ProtoDemo.Student parseFrom(
				com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(com.moca.testprotobuf.proto.ProtoDemo.Student prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code proto.Student}
		 */
		public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder>
				implements com.moca.testprotobuf.proto.ProtoDemo.StudentOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return com.moca.testprotobuf.proto.ProtoDemo.internal_static_proto_Student_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return com.moca.testprotobuf.proto.ProtoDemo.internal_static_proto_Student_fieldAccessorTable
						.ensureFieldAccessorsInitialized(com.moca.testprotobuf.proto.ProtoDemo.Student.class,
								com.moca.testprotobuf.proto.ProtoDemo.Student.Builder.class);
			}

			// Construct using com.moca.testprotobuf.proto.ProtoDemo.Student.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
					getPhoneFieldBuilder();
				}
			}

			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				id_ = 0;
				bitField0_ = (bitField0_ & ~0x00000001);
				name_ = "";
				bitField0_ = (bitField0_ & ~0x00000002);
				email_ = "";
				bitField0_ = (bitField0_ & ~0x00000004);
				sex_ = com.moca.testprotobuf.proto.ProtoDemo.Student.Sex.MAN;
				bitField0_ = (bitField0_ & ~0x00000008);
				if (phoneBuilder_ == null) {
					phone_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000010);
				} else {
					phoneBuilder_.clear();
				}
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return com.moca.testprotobuf.proto.ProtoDemo.internal_static_proto_Student_descriptor;
			}

			public com.moca.testprotobuf.proto.ProtoDemo.Student getDefaultInstanceForType() {
				return com.moca.testprotobuf.proto.ProtoDemo.Student.getDefaultInstance();
			}

			public com.moca.testprotobuf.proto.ProtoDemo.Student build() {
				com.moca.testprotobuf.proto.ProtoDemo.Student result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			public com.moca.testprotobuf.proto.ProtoDemo.Student buildPartial() {
				com.moca.testprotobuf.proto.ProtoDemo.Student result = new com.moca.testprotobuf.proto.ProtoDemo.Student(
						this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.id_ = id_;
				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
					to_bitField0_ |= 0x00000002;
				}
				result.name_ = name_;
				if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
					to_bitField0_ |= 0x00000004;
				}
				result.email_ = email_;
				if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
					to_bitField0_ |= 0x00000008;
				}
				result.sex_ = sex_;
				if (phoneBuilder_ == null) {
					if (((bitField0_ & 0x00000010) == 0x00000010)) {
						phone_ = java.util.Collections.unmodifiableList(phone_);
						bitField0_ = (bitField0_ & ~0x00000010);
					}
					result.phone_ = phone_;
				} else {
					result.phone_ = phoneBuilder_.build();
				}
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof com.moca.testprotobuf.proto.ProtoDemo.Student) {
					return mergeFrom((com.moca.testprotobuf.proto.ProtoDemo.Student) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(com.moca.testprotobuf.proto.ProtoDemo.Student other) {
				if (other == com.moca.testprotobuf.proto.ProtoDemo.Student.getDefaultInstance())
					return this;
				if (other.hasId()) {
					setId(other.getId());
				}
				if (other.hasName()) {
					bitField0_ |= 0x00000002;
					name_ = other.name_;
					onChanged();
				}
				if (other.hasEmail()) {
					bitField0_ |= 0x00000004;
					email_ = other.email_;
					onChanged();
				}
				if (other.hasSex()) {
					setSex(other.getSex());
				}
				if (phoneBuilder_ == null) {
					if (!other.phone_.isEmpty()) {
						if (phone_.isEmpty()) {
							phone_ = other.phone_;
							bitField0_ = (bitField0_ & ~0x00000010);
						} else {
							ensurePhoneIsMutable();
							phone_.addAll(other.phone_);
						}
						onChanged();
					}
				} else {
					if (!other.phone_.isEmpty()) {
						if (phoneBuilder_.isEmpty()) {
							phoneBuilder_.dispose();
							phoneBuilder_ = null;
							phone_ = other.phone_;
							bitField0_ = (bitField0_ & ~0x00000010);
							phoneBuilder_ = com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders
									? getPhoneFieldBuilder()
									: null;
						} else {
							phoneBuilder_.addAllMessages(other.phone_);
						}
					}
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			public final boolean isInitialized() {
				if (!hasId()) {

					return false;
				}
				if (!hasName()) {

					return false;
				}
				for (int i = 0; i < getPhoneCount(); i++) {
					if (!getPhone(i).isInitialized()) {

						return false;
					}
				}
				return true;
			}

			public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				com.moca.testprotobuf.proto.ProtoDemo.Student parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (com.moca.testprotobuf.proto.ProtoDemo.Student) e.getUnfinishedMessage();
					throw e;
				} finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private int bitField0_;

			// required int32 id = 1;
			private int id_;

			/**
			 * <code>required int32 id = 1;</code>
			 */
			public boolean hasId() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			/**
			 * <code>required int32 id = 1;</code>
			 */
			public int getId() {
				return id_;
			}

			/**
			 * <code>required int32 id = 1;</code>
			 */
			public Builder setId(int value) {
				bitField0_ |= 0x00000001;
				id_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>required int32 id = 1;</code>
			 */
			public Builder clearId() {
				bitField0_ = (bitField0_ & ~0x00000001);
				id_ = 0;
				onChanged();
				return this;
			}

			// required string name = 2;
			private java.lang.Object name_ = "";

			/**
			 * <code>required string name = 2;</code>
			 */
			public boolean hasName() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}

			/**
			 * <code>required string name = 2;</code>
			 */
			public java.lang.String getName() {
				java.lang.Object ref = name_;
				if (!(ref instanceof java.lang.String)) {
					java.lang.String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
					name_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>required string name = 2;</code>
			 */
			public com.google.protobuf.ByteString getNameBytes() {
				java.lang.Object ref = name_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					name_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>required string name = 2;</code>
			 */
			public Builder setName(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000002;
				name_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>required string name = 2;</code>
			 */
			public Builder clearName() {
				bitField0_ = (bitField0_ & ~0x00000002);
				name_ = getDefaultInstance().getName();
				onChanged();
				return this;
			}

			/**
			 * <code>required string name = 2;</code>
			 */
			public Builder setNameBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000002;
				name_ = value;
				onChanged();
				return this;
			}

			// optional string email = 3;
			private java.lang.Object email_ = "";

			/**
			 * <code>optional string email = 3;</code>
			 */
			public boolean hasEmail() {
				return ((bitField0_ & 0x00000004) == 0x00000004);
			}

			/**
			 * <code>optional string email = 3;</code>
			 */
			public java.lang.String getEmail() {
				java.lang.Object ref = email_;
				if (!(ref instanceof java.lang.String)) {
					java.lang.String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
					email_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>optional string email = 3;</code>
			 */
			public com.google.protobuf.ByteString getEmailBytes() {
				java.lang.Object ref = email_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					email_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>optional string email = 3;</code>
			 */
			public Builder setEmail(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000004;
				email_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>optional string email = 3;</code>
			 */
			public Builder clearEmail() {
				bitField0_ = (bitField0_ & ~0x00000004);
				email_ = getDefaultInstance().getEmail();
				onChanged();
				return this;
			}

			/**
			 * <code>optional string email = 3;</code>
			 */
			public Builder setEmailBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000004;
				email_ = value;
				onChanged();
				return this;
			}

			// optional .proto.Student.Sex sex = 4 [default = MAN];
			private com.moca.testprotobuf.proto.ProtoDemo.Student.Sex sex_ = com.moca.testprotobuf.proto.ProtoDemo.Student.Sex.MAN;

			/**
			 * <code>optional .proto.Student.Sex sex = 4 [default = MAN];</code>
			 */
			public boolean hasSex() {
				return ((bitField0_ & 0x00000008) == 0x00000008);
			}

			/**
			 * <code>optional .proto.Student.Sex sex = 4 [default = MAN];</code>
			 */
			public com.moca.testprotobuf.proto.ProtoDemo.Student.Sex getSex() {
				return sex_;
			}

			/**
			 * <code>optional .proto.Student.Sex sex = 4 [default = MAN];</code>
			 */
			public Builder setSex(com.moca.testprotobuf.proto.ProtoDemo.Student.Sex value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000008;
				sex_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>optional .proto.Student.Sex sex = 4 [default = MAN];</code>
			 */
			public Builder clearSex() {
				bitField0_ = (bitField0_ & ~0x00000008);
				sex_ = com.moca.testprotobuf.proto.ProtoDemo.Student.Sex.MAN;
				onChanged();
				return this;
			}

			// repeated .proto.Student.PhoneNumber phone = 5;
			private java.util.List<com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber> phone_ = java.util.Collections
					.emptyList();

			private void ensurePhoneIsMutable() {
				if (!((bitField0_ & 0x00000010) == 0x00000010)) {
					phone_ = new java.util.ArrayList<com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber>(phone_);
					bitField0_ |= 0x00000010;
				}
			}

			private com.google.protobuf.RepeatedFieldBuilder<com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber, com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber.Builder, com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumberOrBuilder> phoneBuilder_;

			/**
			 * <code>repeated .proto.Student.PhoneNumber phone = 5;</code>
			 */
			public java.util.List<com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber> getPhoneList() {
				if (phoneBuilder_ == null) {
					return java.util.Collections.unmodifiableList(phone_);
				} else {
					return phoneBuilder_.getMessageList();
				}
			}

			/**
			 * <code>repeated .proto.Student.PhoneNumber phone = 5;</code>
			 */
			public int getPhoneCount() {
				if (phoneBuilder_ == null) {
					return phone_.size();
				} else {
					return phoneBuilder_.getCount();
				}
			}

			/**
			 * <code>repeated .proto.Student.PhoneNumber phone = 5;</code>
			 */
			public com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber getPhone(int index) {
				if (phoneBuilder_ == null) {
					return phone_.get(index);
				} else {
					return phoneBuilder_.getMessage(index);
				}
			}

			/**
			 * <code>repeated .proto.Student.PhoneNumber phone = 5;</code>
			 */
			public Builder setPhone(int index, com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber value) {
				if (phoneBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensurePhoneIsMutable();
					phone_.set(index, value);
					onChanged();
				} else {
					phoneBuilder_.setMessage(index, value);
				}
				return this;
			}

			/**
			 * <code>repeated .proto.Student.PhoneNumber phone = 5;</code>
			 */
			public Builder setPhone(int index,
					com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber.Builder builderForValue) {
				if (phoneBuilder_ == null) {
					ensurePhoneIsMutable();
					phone_.set(index, builderForValue.build());
					onChanged();
				} else {
					phoneBuilder_.setMessage(index, builderForValue.build());
				}
				return this;
			}

			/**
			 * <code>repeated .proto.Student.PhoneNumber phone = 5;</code>
			 */
			public Builder addPhone(com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber value) {
				if (phoneBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensurePhoneIsMutable();
					phone_.add(value);
					onChanged();
				} else {
					phoneBuilder_.addMessage(value);
				}
				return this;
			}

			/**
			 * <code>repeated .proto.Student.PhoneNumber phone = 5;</code>
			 */
			public Builder addPhone(int index, com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber value) {
				if (phoneBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensurePhoneIsMutable();
					phone_.add(index, value);
					onChanged();
				} else {
					phoneBuilder_.addMessage(index, value);
				}
				return this;
			}

			/**
			 * <code>repeated .proto.Student.PhoneNumber phone = 5;</code>
			 */
			public Builder addPhone(com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber.Builder builderForValue) {
				if (phoneBuilder_ == null) {
					ensurePhoneIsMutable();
					phone_.add(builderForValue.build());
					onChanged();
				} else {
					phoneBuilder_.addMessage(builderForValue.build());
				}
				return this;
			}

			/**
			 * <code>repeated .proto.Student.PhoneNumber phone = 5;</code>
			 */
			public Builder addPhone(int index,
					com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber.Builder builderForValue) {
				if (phoneBuilder_ == null) {
					ensurePhoneIsMutable();
					phone_.add(index, builderForValue.build());
					onChanged();
				} else {
					phoneBuilder_.addMessage(index, builderForValue.build());
				}
				return this;
			}

			/**
			 * <code>repeated .proto.Student.PhoneNumber phone = 5;</code>
			 */
			public Builder addAllPhone(
					java.lang.Iterable<? extends com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber> values) {
				if (phoneBuilder_ == null) {
					ensurePhoneIsMutable();
					super.addAll(values, phone_);
					onChanged();
				} else {
					phoneBuilder_.addAllMessages(values);
				}
				return this;
			}

			/**
			 * <code>repeated .proto.Student.PhoneNumber phone = 5;</code>
			 */
			public Builder clearPhone() {
				if (phoneBuilder_ == null) {
					phone_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000010);
					onChanged();
				} else {
					phoneBuilder_.clear();
				}
				return this;
			}

			/**
			 * <code>repeated .proto.Student.PhoneNumber phone = 5;</code>
			 */
			public Builder removePhone(int index) {
				if (phoneBuilder_ == null) {
					ensurePhoneIsMutable();
					phone_.remove(index);
					onChanged();
				} else {
					phoneBuilder_.remove(index);
				}
				return this;
			}

			/**
			 * <code>repeated .proto.Student.PhoneNumber phone = 5;</code>
			 */
			public com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber.Builder getPhoneBuilder(int index) {
				return getPhoneFieldBuilder().getBuilder(index);
			}

			/**
			 * <code>repeated .proto.Student.PhoneNumber phone = 5;</code>
			 */
			public com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumberOrBuilder getPhoneOrBuilder(int index) {
				if (phoneBuilder_ == null) {
					return phone_.get(index);
				} else {
					return phoneBuilder_.getMessageOrBuilder(index);
				}
			}

			/**
			 * <code>repeated .proto.Student.PhoneNumber phone = 5;</code>
			 */
			public java.util.List<? extends com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumberOrBuilder> getPhoneOrBuilderList() {
				if (phoneBuilder_ != null) {
					return phoneBuilder_.getMessageOrBuilderList();
				} else {
					return java.util.Collections.unmodifiableList(phone_);
				}
			}

			/**
			 * <code>repeated .proto.Student.PhoneNumber phone = 5;</code>
			 */
			public com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber.Builder addPhoneBuilder() {
				return getPhoneFieldBuilder()
						.addBuilder(com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber.getDefaultInstance());
			}

			/**
			 * <code>repeated .proto.Student.PhoneNumber phone = 5;</code>
			 */
			public com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber.Builder addPhoneBuilder(int index) {
				return getPhoneFieldBuilder().addBuilder(index,
						com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber.getDefaultInstance());
			}

			/**
			 * <code>repeated .proto.Student.PhoneNumber phone = 5;</code>
			 */
			public java.util.List<com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber.Builder> getPhoneBuilderList() {
				return getPhoneFieldBuilder().getBuilderList();
			}

			private com.google.protobuf.RepeatedFieldBuilder<com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber, com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber.Builder, com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumberOrBuilder> getPhoneFieldBuilder() {
				if (phoneBuilder_ == null) {
					phoneBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber, com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumber.Builder, com.moca.testprotobuf.proto.ProtoDemo.Student.PhoneNumberOrBuilder>(
							phone_, ((bitField0_ & 0x00000010) == 0x00000010), getParentForChildren(), isClean());
					phone_ = null;
				}
				return phoneBuilder_;
			}

			// @@protoc_insertion_point(builder_scope:proto.Student)
		}

		static {
			defaultInstance = new Student(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:proto.Student)
	}

	private static com.google.protobuf.Descriptors.Descriptor internal_static_proto_Student_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_proto_Student_fieldAccessorTable;
	private static com.google.protobuf.Descriptors.Descriptor internal_static_proto_Student_PhoneNumber_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_proto_Student_PhoneNumber_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		java.lang.String[] descriptorData = { "\n)com/moca/testprotobuf/proto/Student.pr"
				+ "oto\022\005proto\"\230\002\n\007Student\022\n\n\002id\030\001 \002(\005\022\014\n\004na"
				+ "me\030\002 \002(\t\022\r\n\005email\030\003 \001(\t\022$\n\003sex\030\004 \001(\0162\022.p"
				+ "roto.Student.Sex:\003MAN\022)\n\005phone\030\005 \003(\0132\032.p"
				+ "roto.Student.PhoneNumber\032K\n\013PhoneNumber\022"
				+ "\016\n\006number\030\001 \002(\t\022,\n\004type\030\002 \001(\0162\030.proto.St"
				+ "udent.PhoneType:\004HOME\"\031\n\003Sex\022\007\n\003MAN\020\000\022\t\n"
				+ "\005WOMAN\020\001\"+\n\tPhoneType\022\n\n\006MOBILE\020\000\022\010\n\004HOM"
				+ "E\020\001\022\010\n\004WORK\020\002B(\n\033com.moca.testprotobuf.p" + "rotoB\tProtoDemo" };
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
			public com.google.protobuf.ExtensionRegistry assignDescriptors(
					com.google.protobuf.Descriptors.FileDescriptor root) {
				descriptor = root;
				internal_static_proto_Student_descriptor = getDescriptor().getMessageTypes().get(0);
				internal_static_proto_Student_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_proto_Student_descriptor,
						new java.lang.String[] { "Id", "Name", "Email", "Sex", "Phone", });
				internal_static_proto_Student_PhoneNumber_descriptor = internal_static_proto_Student_descriptor
						.getNestedTypes().get(0);
				internal_static_proto_Student_PhoneNumber_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_proto_Student_PhoneNumber_descriptor,
						new java.lang.String[] { "Number", "Type", });
				return null;
			}
		};
		com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
				new com.google.protobuf.Descriptors.FileDescriptor[] {}, assigner);
	}

	// @@protoc_insertion_point(outer_class_scope)
}
